#pragma once

#include "common.h"

// TODO: implement these
#define SHDRT_INTENT_FLAGS_LIST(X) \
	/* --- Activity Management Flags --- */ \
	X(SHDRT_INTENT_FLAG_ACTIVITY_NEW_TASK) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_SINGLE_TOP) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_CLEAR_TOP) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_CLEAR_TASK) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_NO_HISTORY) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_REORDER_TO_FRONT) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_FORWARD_RESULT) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_NO_ANIMATION) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_MULTIPLE_TASK) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_LAUNCH_ADJACENT) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_BROUGHT_TO_FRONT) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_RESET_TASK_IF_NEEDED) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_PREVIOUS_IS_TOP) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_NO_USER_ACTION) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_TASK_ON_HOME) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_MATCH_EXTERNAL) \
	X(SHDRT_INTENT_FLAG_ACTIVITY_RETAIN_IN_RECENTS) \
	/* --- Grant / Permission Flags --- */ \
	X(SHDRT_INTENT_FLAG_GRANT_READ_URI_PERMISSION) \
	X(SHDRT_INTENT_FLAG_GRANT_WRITE_URI_PERMISSION) \
	X(SHDRT_INTENT_FLAG_GRANT_PERSISTABLE_URI_PERMISSION) \
	X(SHDRT_INTENT_FLAG_GRANT_PREFIX_URI_PERMISSION) \
	/* --- Broadcast Receiver Flags --- */ \
	X(SHDRT_INTENT_FLAG_RECEIVER_FOREGROUND) \
	X(SHDRT_INTENT_FLAG_RECEIVER_REGISTERED_ONLY) \
	X(SHDRT_INTENT_FLAG_RECEIVER_REPLACE_PENDING) \
	X(SHDRT_INTENT_FLAG_RECEIVER_NO_ABORT) \
	X(SHDRT_INTENT_FLAG_RECEIVER_VISIBLE_TO_INSTANT_APPS) \
	X(SHDRT_INTENT_FLAG_INCLUDE_STOPPED_PACKAGES) \
	X(SHDRT_INTENT_FLAG_EXCLUDE_STOPPED_PACKAGES) \
	/* --- Debugging & Misc Flags --- */ \
	X(SHDRT_INTENT_FLAG_DEBUG_LOG_RESOLUTION) \
	X(SHDRT_INTENT_FLAG_FROM_BACKGROUND) \
	X(SHDRT_INTENT_FLAG_IGNORE_CHEEK_PRESSES)
#define SHDRT_INTENT_FLAGS_COUNT (0 SHDRT_INTENT_FLAGS_LIST(COUNT_ITEMS))

#define T shdrt_IntentBitset, SHDRT_INTENT_FLAGS_COUNT
#include <stc/cbits.h>
#undef T

typedef enum {
#define GENERATE_ENUM(name) name,
	SHDRT_INTENT_FLAGS_LIST(GENERATE_ENUM)
#undef GENERATE_ENUM
} shdrt_IntentFlags;
